### PR TITLE
Fixed to work in conjunction with releases

### PR DESCRIPTION
**Pull request by ztmr**
When the OTP release mechanism is involved, `rebar_vsn_plugin` fails on `reltool.config` so that's what we've fixed here.

We also changed the autogenerated comment in the resulting `.app` file to let people know that it was generated by this plugin. Since we don't expect anybody to edit this (generated) file, Emacs mode settings are not necessary there and was removed thus.

To be honest, I originally wanted to submit pull request that contains only the first commit (a5db014) but GitHub does not allow me to make a pull-request from anything else than from the master's HEAD :-(

### CODE REVIEW

**Comment by ericbmerritt** [comment]
@ztmr over all just minor comments. However, you do need to rebase on the latest version of the plugin.

**Comment by ztmr** [comment]
ah, that's good idea (to rebase) :-) just a second.
BTW, the changes are quite old so I had no idea there are coding style incompatibilities when I submitted the pull request :-(

**Comment by ztmr** [comment]
Well, this should be better...

**Comment by ericbmerritt** [comment]
@ztmr no worries on needing to respond to comment. My pull requests (which other erlware guys review) almost always have things that need fixing as well. btw, still a couple of minor pieces of commented out code left.

**Comment by ericbmerritt** [comment]
finally squash b91b706 and 9b19399. Let me know if this gets too annoying for you. I can always take these patches and make the changes myself.

**Comment by ericbmerritt** [comment]
@ztmr this looks good. I will try to grab some time to test it. However, it probably wont be before tomorrow.

**Comment by jwilberding** [comment]
@ztmr Thanks for the patches, much appreciated!

**Pull request merged**
