### PR TITLE
Add support for new format tag

### PR DESCRIPTION
**Pull request by platinumthinker**
New logic calculate vsn when tag 0.0.0.0 or 0.0.0 (increment count commit from last tag when 0.0.0.0 and append when 0.0.0)

### CODE REVIEW

**Comment by ericbmerritt** [comment]
the main goal of this repo is to follow semver. Allowing non-semver compatibile versions moves us away from that. Its probably ok, considering that version comparison will continue to work. Hmm, @tsloughter @jwilberding  what do you guys think?

**Comment by jwilberding** [comment]
I think we probably are going to have to allow it. Rebar3 basically assumes people can't version well in erlang, since they can't. I don't think we are going to win the semver fight outright any time soon, so supporting the right way and tolerating some aspects of the wrong way is what need to do I guess.

**Comment by martinjlogan** [comment]
sounds reasonable to me

On Thu, Apr 2, 2015 at 1:29 PM, Jordan Wilberding notifications@github.com
wrote:

> I think we probably are going to have to allow it. Rebar3 basically
> assumes people can't version well in erlang, since they can't. I don't
> think we are going to win the semver fight outright any time soon, so
> supporting the right way and tolerating some aspects of the wrong way is
> what need to do I guess.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/erlware/rebar_vsn_plugin/pull/22#issuecomment-89002623
> .

## 

Martin Logan
Erlang & OTP in Action (Manning) http://manning.com/logan
http://twitter.com/martinjlogan
http://erlware.org

**Comment by ericbmerritt** [comment]
I am not trying to win the semver fight. I have always put out that we keep our standards high. Since this has historically been at tool for our use that we simply open source, I have not cared about wide adoption. That said, I am not sure I feel super strongly.

**Comment by platinumthinker** [comment]
> >  platinumthinker commented on Oct 3, 2014 
> >   ericbmerritt commented 5 days ago 
> > You response is super slow. =)

**Comment by ericbmerritt** [comment]
@platinumthinker yes it is. sorry about that :/

**Pull request closed without merging**
